package testclasses;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;

public class TestNG_ReportsAndLogs {
	
//TestNG provides Reporter mechanism to log the statements 
//and these statement go into the reports that are generated by TestNG automatically
	
	@BeforeClass
	public void setUp() {
		System.out.println("\nTestNG_ReportsAndLogs -->This runs once before class");
		Reporter.log("\nTestNG_ReportsAndLogs -->This runs once before class",false); //true > prints to console
	}
	
	@BeforeMethod
	public void beforeMethod() {
		Reporter.log("\nTestNG_ReportsAndLogs -->This runs once before every method",true);
	}
	
	@Test
	public void testMethod1() {
		Reporter.log("\nRunning Test -->TestNG_ReportsAndLogs -->Test Method1",true);
	}

	@Test
	public void testMethod2() {
		Reporter.log("\nRunning Test -->TestNG_ReportsAndLogs -->Test Method2",true);
		Assert.assertTrue(false);
	}
	
	@Test(dependsOnMethods={"testMethod2"})
	public void testMetho3() {
		Reporter.log("\nRunning Test -->TestNG_ReportsAndLogs -->Test Method3",true);
	}

	@AfterMethod
	public void afterMethod() {
		Reporter.log("\nTestNG_ReportsAndLogs -->This runs once after every method",true);
	}
	
	@AfterClass
	public void cleanUp() {
		Reporter.log("\nTestNG_ReportsAndLogs -->This runs once after class",true);
	}

}
